name: Deploy to Dev
on:
  workflow_run:
    workflows: ['Unit tests & linter']
    branches: [develop]
    types:
      - completed

jobs:
  deploy-to-dev:
    uses: ./.github/workflows/deploy-app-workflow.yml
    with:
      environment: DEV
      branch: develop
    secrets:
      app_env: ${{ secrets.DEV_APP_ENV }}
      ssh_private_key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
      ssh_host: ${{ secrets.DEV_SSH_HOST }}
      ssh_user: ${{ secrets.SSH_USER }}
