name: 'Unit tests & linter'
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  validations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - run: yarn install --immutable --immutable-cache

      - name: Run ESLint
        run: yarn lint

      - name: Run tests
        run: yarn test --maxWorkers=4 --no-color --coverage=false --changedSince=origin/main
